
# IDK why but node-18 does not create the openssl issue
FROM node:22-slim 
ARG TEST_DB_PORT 
ARG TEST_DB_NAME
ARG TEST_BACKEND_PORT

# Install dependencies for Prisma, this may not be needed with different versions of node
RUN apt-get update -y
RUN apt-get install -y openssl

# Set the working directory
WORKDIR /usr/server/ 

# Copy the package.json and package-lock.json files
COPY package.json /usr/server/package.json
COPY package-lock.json /usr/server/package-lock.json

RUN npm ci

COPY . /usr/server/

EXPOSE ${TEST_BACKEND_PORT} 

CMD ["npm", "run", "test"]
