# Use the official Node.js image from Docker Hub
FROM node:20-slim 

# Arguments for database and backend configurations
ARG DB_PORT 
ARG DB_NAME
ARG BACKEND_PORT

ENV NODE_ENV=dev

# Install dependencies for Prisma
RUN apt-get update -y && \
    apt-get install -y openssl netcat-openbsd && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

# Set the working directory
WORKDIR /usr/server/ 

# Copy the package.json and package-lock.json files
COPY package.json /usr/server/package.json
COPY package-lock.json /usr/server/package-lock.json

# Install the dependencies
RUN npm ci

# Copy the rest of the application source code to the working directory
COPY . /usr/server/

# Expose the backend port
EXPOSE ${BACKEND_PORT}

# Run the commands needed to generate Prisma client, push the database schema, run migrations, and seed the database
CMD npm run prisma:push && npm run seed && npm run dev:watch
