
# IDK why but node-18 does not create the openssl issue
FROM node:22-slim 

# Arguments for database and backend configurations
ARG TEST_DB_PORT 
ARG TEST_DB_NAME
ARG TEST_BACKEND_PORT

# nstall openSSL for prisma, and netcat for testing
RUN apt-get update -y && \
    apt-get install -y netcat-openbsd && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

# Set the working directory
WORKDIR /usr/server/ 

# Copy the package.json and package-lock.json files
COPY package.json /usr/server/package.json
COPY package-lock.json /usr/server/package-lock.json

RUN npm ci

COPY . /usr/server/

EXPOSE ${TEST_BACKEND_PORT} 

CMD ["npm", "run", "start:test"]
