// src/lib/data.js
export const classesData = [
    {
      id: '1',
      name: "COSC 414",
      instructor: "Shan Du",
      numStudents: 30,
      numAssignments: 5,
      numPeerReviews: 3,
    },
    {
      id: '2',
      name: "MATH 222",
      instructor: "Paul Tsomone",
      numStudents: 25,
      numAssignments: 4,
      numPeerReviews: 2,
    },
    {
      id: '3',
      name: "COSC 221",
      instructor: "Mohammed Khaled",
      numStudents: 40,
      numAssignments: 6,
      numPeerReviews: 4,
    },
    {
      id: '4',
      name: "PHYS 110",
      instructor: "John Doe",
      numStudents: 35,
      numAssignments: 3,
      numPeerReviews: 2,
    },
    {
      id: '5',
      name: "CHEM 101",
      instructor: "Jane Smith",
      numStudents: 28,
      numAssignments: 5,
      numPeerReviews: 3,
    },
    // {
    //   id: '6',
    //   name: "HIST 201",
    //   instructor: "Albert Johnson",
    //   numStudents: 22,
    //   numAssignments: 4,
    //   numPeerReviews: 2,
    // },
    // Add more classes as needed
];

export const assignmentsData = [
    {
      id: '1',
      name: "Integral Calculations",
      className: "Math 101",
      dueDate: "03/14/25",
      description: "Assignment on integral calculations.",
      shortDesc: "Calculating integrals.",
      peerReviewsDone: 2,
      peerReviewDueDate: "03/21/25",
      forReview: true,
    },
    {
      id: '2',
      name: "Linear Algebra",
      className: "Math 202",
      dueDate: "04/22/25",
      description: "Assignment on linear algebra.",
      shortDesc: "Linear algebra basics.",
      peerReviewsDone: 1,
      peerReviewDueDate: "04/29/25",
      forReview: false,
    },
    {
      id: '3',
      name: "Data Structures",
      className: "CS 303",
      dueDate: "05/11/25",
      description: "Assignment on data structures.",
      shortDesc: "Exploring data structures.",
      peerReviewsDone: 3,
      peerReviewDueDate: "05/18/25",
      forReview: true,
    },
    {
      id: '4',
      name: "Electromagnetic Theory",
      className: "PHYS 110",
      dueDate: "03/30/25",
      description: "Assignment on electromagnetic theory.",
      shortDesc: "Understanding electromagnetic waves.",
      peerReviewsDone: 1,
      peerReviewDueDate: "04/05/25",
      forReview: true,
    },
    {
      id: '5',
      name: "Chemical Reactions",
      className: "CHEM 101",
      dueDate: "04/15/25",
      description: "Assignment on chemical reactions.",
      shortDesc: "Balancing chemical equations.",
      peerReviewsDone: 0,
      peerReviewDueDate: "04/22/25",
      forReview: true,
    },
    {
      id: '6',
      name: "World War II",
      className: "HIST 201",
      dueDate: "05/20/25",
      description: "Assignment on World War II.",
      shortDesc: "Analyzing key events of WWII.",
      peerReviewsDone: 2,
      peerReviewDueDate: "05/27/25",
      forReview: false,
    },
    {
      id: '7',
      name: "Quantum Mechanics",
      className: "PHYS 110",
      dueDate: "04/10/25",
      description: "Assignment on quantum mechanics.",
      shortDesc: "Introduction to quantum theory.",
      peerReviewsDone: 3,
      peerReviewDueDate: "04/17/25",
      forReview: false,
    },
    {
      id: '8',
      name: "Organic Chemistry",
      className: "CHEM 101",
      dueDate: "04/25/25",
      description: "Assignment on organic chemistry.",
      shortDesc: "Basics of organic compounds.",
      peerReviewsDone: 1,
      peerReviewDueDate: "05/02/25",
      forReview: false,
    },
    // Add more assignments as needed
];
