name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
    - name: Save the Docker image to a tar file
      run: |
        mkdir -p build
        docker save -o build/peer-review-webapp_$(date +%s).tar peer-review-webapp:$(date +%s)
